name: docs
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v3

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: pip install requests PyYAML

    # Example of fetch step — replace with your actual commands
    - name: Fetch Verilog and build config
      run: |
        echo "Fetching Verilog from Wokwi API..."
        # curl or wget commands go here
        # python scripts to build config if needed

    # Make script executable
    - name: Make configure.py executable
      run: chmod +x configure.py

    # Run script
    - name: Run configure
      run: ./configure.py --check-docs
