name: docs
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  docs:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3

    # need python
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests PyYAML

    # fetch the Verilog from Wokwi API
    - name: fetch Verilog and build config
    - name: Make configure.py executable
      run: chmod +x configure.py
    - name: run python

      run: ./configure.py --check-docs
